MAINTAINER Ryan Olson rolson@nvidia.com

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ruby-dev libpam0g-dev libmysqlclient-dev \
        libmunge-dev libmysqld-dev wget python-minimal && \
    rm -rf /var/lib/apt/lists/*

RUN gem install fpm

ARG SLURM_VERSION=17.02.5
ARG APT_VERSION=1.0

RUN wget http://www.schedmd.com/downloads/latest/slurm-$SLURM_VERSION.tar.bz2 \
 && tar xvjf slurm-$SLURM_VERSION.tar.bz2 \
 && rm -f slurm-$SLURM_VERSION.tar.bz2 \
 && cd slurm-$SLURM_VERSION \
 && ./configure --prefix=/tmp/slurm-build --sysconfdir=/etc/slurm \
 && make -j \
 && make -j contrib \
 && make -j install 

RUN fpm -s dir -t deb -v $APT_VERSION -n slurm-${SLURM_VERSION} --prefix=/usr -C /tmp/slurm-build . \
 && dpkg --contents slurm-${SLURM_VERSION}_${APT_VERSION}_amd64.deb
